apiVersion: apps/v1
kind: Deployment
metadata:
  name: Angular-ApexCharts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Angular-ApexCharts 
  template:
    metadata:
      labels:
        app: Angular-ApexCharts
    spec:
      containers:
        - name: Angular-ApexCharts-container
          image: nibrassehmidi/angular_k8s_test:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: Angular-ApexCharts-service
spec:
  selector:
    app: Angular-ApexCharts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
