apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-k8s-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-k8s-test 
  template:
    metadata:
      labels:
        app: angular-k8s-test
    spec:
      containers:
        - name: angular-k8s-test
          image: nibrassehmidi/angular_k8s_test:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-test-service
spec:
  selector:
    app: angular-k8s-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
